# Generated by Django 4.2.7 on 2023-11-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='couleur',
        ),
        migrations.RemoveField(
            model_name='article',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='article',
            name='prix',
        ),
        migrations.AddField(
            model_name='article',
            name='color',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
