# Generated by Django 4.2.7 on 2023-11-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_remove_article_couleur_remove_article_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='color',
            field=models.CharField(default='Couleur par défaut', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(default='Nom par défaut', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
