# Generated by Django 4.2.7 on 2023-11-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_alter_article_color_alter_article_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
